import 'package:skyfy/src/tools/bnb/images.dart';

const t6IcActivity = "assets/images/bnb/t6_ic_activity.svg";
const t6IcBoxing = "assets/images/bnb/t6_ic_boxing.svg";
const t6IcCycle = "assets/images/bnb/t6_ic_cycle.svg";
const t6IcList = "assets/images/bnb/t6_ic_list.svg";
const t6IcLogo = "$baseUrl/images/theme6/t6_ic_logo.png";
const t6IcProfile = "$baseUrl/images/theme6/t6_ic_profile.jpg";
const t6IcRunning = "assets/images/bnb/t6_ic_running.svg";
const t6IcSleep = "assets/images/bnb/t6_ic_sleep.svg";
const t6IcSwim = "assets/images/bnb/t6_ic_swim.svg";
const t6IcWalk = "assets/images/bnb/t6_ic_walk.svg";
const t6IcWalk1 = "$baseUrl/images/theme6/t6_ic_walk1.png";
const t6IcWalk2 = "$baseUrl/images/theme6/t6_ic_walk2.png";
const t6IcWork1 = "$baseUrl/images/theme6/t6_ic_work1.jpg";
const t6IcWork4 = "$baseUrl/images/theme6/t6_ic_work4.png";
const t6IcWork2 = "$baseUrl/images/theme6/t6_ic_work2.jpeg";
const t6IcZumba = "assets/images/bnb/t6_ic_zumba.svg";
const t6IcMeal = "assets/images/bnb/t6_ic_meal.svg";
const t6IcWork3 = "$baseUrl/images/theme6/t6_ic_work3.jpg";
const t6FacebookFill = "assets/images/bnb/t6_facebook_fill.svg";
const t6GoogleFill = "assets/images/bnb/t6_google_fill.svg";
const t6IcWorkBn = "assets/images/bnb/t6_ic_work_bn.svg";
const headProfile = "assets/images/bnb/HeadProfile.svg";
