// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrn-7WFw4f1Mkwl9v_e8R8qO1RrFNAtEw',
    appId: '1:854667580923:android:02a98cf781e3aa7d2f275e',
    messagingSenderId: '854667580923',
    projectId: 'skyfy-83dd4',
    storageBucket: 'skyfy-83dd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA50BGYLF5mc6DLCqRnVmuTfL_KZfgKcp4',
    appId: '1:854667580923:ios:8d92798f5b50b89b2f275e',
    messagingSenderId: '854667580923',
    projectId: 'skyfy-83dd4',
    storageBucket: 'skyfy-83dd4.appspot.com',
    androidClientId: '854667580923-arhj94q8u9tq9mg5poqt069o2c4hg1eo.apps.googleusercontent.com',
    iosClientId: '854667580923-i7v6cuh4ug7mm0nhsf11si0f7uos5s0l.apps.googleusercontent.com',
    iosBundleId: 'tech.dev-studio.skyfy',
  );
}
